language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules
os:
  - linux
install:
  - npm install
script:
  - npm run compile
deploy:
  provider: npm
  email: objectisnotdefined@gmail.com
  on:
    branch: master
  api_key:
    secure: bqvoyZoG95E2jpaElamTq99sI+JnmN5EZT1TZEdktqkR5aZS4MqaA5bcajTVRgp9tGsYVzL3CoRkz6OAQXGcy4nsuyqlO7+nz9fHfQuhSsoRtnjI+ziJIeC4aM7ptz7JJ2YxrBgQjLCtDkxBAJwaVMwJBt0tYAb0bx1CQwJfpPvQxwjPLeQq0+NNmU+ZlMqxz4qpYWmoDaBBLjPT+KogwgOLDd7mmWnAsVFuv8q9NUUHkWmU0gzOm2kX19CwXTqcMGFAC+rY3K7LpM7CB4Ohyg2HccF15fiBqtySQmmxgdrDQjfOsUFFjzjOZWCWcBJOt1qHtQTO57ubDTBSlVCYSZrXfUN9yycYw0vBPgfF2xKHg9SgaLL7g6KIflzjevUSvZZjuh5ZMM7R4P2L/roZujNAXpmTB/QzePJT1hrzUKczUfHn5itEEacFqfotD+rMvzJ244jBUpNdS3XV4QX9r2ISDGS4pFcXzWz+Qb+I+Xna+n09sWRedX4tzfTAyFvaSa1jgvptOtFSVX4VgtKOgjKLCtHsNEWEMZWCnEaL0341wMFbipP8rkNwGYX/+fuIWy4v6i19uwEM5C59Mo5yXq7TmI/FkWTrjAUyreNaHL4zdbd/4uU1mM1hYbdhm/ZwxnxawuN7ZWAW8MuB7f5GHYUTw+T3Q8LwZbSHJ5OPhRk=
